"""Typed boundary for the recovered ingestion implementation.

The runtime module predates the strict package and remains intentionally
unchanged internally during repository consolidation. This stub makes its
stable public document/CLI contract explicit without a risky algorithm rewrite.
"""

from argparse import ArgumentParser
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any

Image: Any
pytesseract: Any
MODO_DOC_ID_RAPIDO: str
MODO_DOC_ID_CONTENIDO: str
RUTA_CACHE_LECTURAS: Path

def limpiar_texto(texto: str) -> str: ...
def obtener_formato(extension: str) -> str: ...
def generar_doc_id(archivo: Path, carpeta_corpus: Path) -> str: ...
def generar_fingerprint_archivo(
    archivo: Path,
    carpeta_corpus: Path,
    modo: str = ...,
) -> dict[str, str]: ...
def obtener_firma_cache(
    archivo: Path, carpeta_corpus: Path
) -> dict[str, object]: ...
def clave_cache(firma: dict[str, object]) -> str: ...
def cargar_cache_lecturas(
    ruta_cache: Path | None,
) -> dict[str, dict[str, object]]: ...
def guardar_cache_lecturas(
    cache: dict[str, dict[str, object]], ruta_cache: Path | None
) -> None: ...
def obtener_fenomeno(archivo: Path, carpeta_corpus: Path) -> int | None: ...
def detectar_idioma(texto: str) -> str: ...
def leer_txt(archivo: Path) -> str: ...
def leer_json(archivo: Path) -> str: ...
def leer_csv(archivo: Path) -> str: ...
def leer_xlsx(archivo: Path) -> str: ...
def leer_html(archivo: Path) -> str: ...
def leer_pdf(archivo: Path, usar_ocr: bool = ...) -> str: ...
def leer_imagen(archivo: Path) -> str: ...
def leer_pbf(
    archivo: Path, fingerprints: set[str] | None = ...
) -> str: ...
def diagnosticar_pbf(
    archivo: Path,
    fingerprints: set[str] | None = ...,
    limite_muestras: int = ...,
) -> dict[str, Any]: ...
def leer_archivo(
    archivo: Path,
    fingerprints_pbf: set[str] | None = ...,
    usar_ocr_pdf: bool = ...,
) -> str: ...
def procesar_corpus(
    carpeta_corpus: Path,
    *,
    max_trabajadores: int = ...,
    max_procesos_pesados: int = ...,
    modo_doc_id: str = ...,
    usar_ocr: bool = ...,
    ruta_cache: Path | None = ...,
    rutas_permitidas: set[str] | None = ...,
    ignorar_cache_lectura: bool = ...,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, int]]: ...
def guardar_jsonl(registros: Iterable[dict[str, Any]], ruta: Path) -> None: ...
def cargar_jsonl(ruta: Path) -> list[dict[str, Any]]: ...
def cargar_rutas_pendientes_ocr(ruta_errores: Path) -> set[str]: ...
def fusionar_por_fuente(
    documentos_base: Sequence[dict[str, Any]],
    documentos_nuevos: Sequence[dict[str, Any]],
) -> list[dict[str, Any]]: ...
def construir_parser() -> ArgumentParser: ...
def main(argv: Sequence[str] | None = ...) -> None: ...
def _ocr_imagen(imagen: Any) -> str: ...
